-- ============================================================
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- 1. Add 'district' and 'unique_id' columns to profiles table
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS district TEXT,
  ADD COLUMN IF NOT EXISTS unique_id TEXT;

-- 2. Add 'district' column to farmers table
ALTER TABLE farmers
  ADD COLUMN IF NOT EXISTS district TEXT;

-- 3. We are removing the sequence from farmers if it forces FRM-001 overriding.
--    By default, if the unique_id column was auto-generated by a trigger, 
--    we need to make sure the app logic overrides it OR we drop the sequence trigger.
--    If there's an existing trigger on farmers for unique_id, this disables it:
-- DROP TRIGGER IF EXISTS set_farmer_unique_id ON farmers;
--    But usually, we can just let the application level specify the unique_id explicitly
--    and it might bypass the trigger if the trigger says `IF NEW.unique_id IS NULL THEN`.
